// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Argparse from "argparse";

function make(version, prog) {
  return new Argparse.ArgumentParser({
              version: version,
              prog: prog
            });
}

function addRequiredArgument(shortName, longName, dest, metavar, parser) {
  parser.addArgument([
        shortName,
        longName
      ], {
        dest: dest,
        metavar: metavar,
        required: true,
        defaultValue: undefined
      });
  
}

function addOptionalArgument(shortName, longName, dest, metavar, $$default, parser) {
  parser.addArgument([
        shortName,
        longName
      ], {
        dest: dest,
        metavar: metavar,
        required: undefined,
        defaultValue: $$default
      });
  
}

export {
  make ,
  addRequiredArgument ,
  addOptionalArgument ,
  
}
/* argparse Not a pure module */
