// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Argparse from "argparse";

function make(version, prog) {
  return new Argparse.ArgumentParser({
              version: version,
              prog: prog
            });
}

function addArgument(name, dest, parser) {
  parser.addArgument(name, {
        dest: dest
      });
  
}

export {
  make ,
  addArgument ,
  
}
/* argparse Not a pure module */
