// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Js_types from "bs-platform/lib/es6/js_types.js";
import * as MimeTypes from "mime-types";

function classify(value) {
  if (Js_types.test(value, /* String */4)) {
    return /* String */Block.__(0, [value]);
  } else {
    return /* Boolean */Block.__(1, [value]);
  }
}

var StringBooleanUnion = {
  classify: classify
};

function contentType(filename) {
  var contentType$1 = classify(MimeTypes.contentType(filename));
  if (contentType$1.tag) {
    return ;
  } else {
    return contentType$1[0];
  }
}

export {
  StringBooleanUnion ,
  contentType ,
  
}
/* mime-types Not a pure module */
