// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Js_types = require("bs-platform/lib/js/js_types.js");
var MimeTypes = require("mime-types");

function string(string$1) {
  return string$1;
}

function $$boolean($$boolean$1) {
  return $$boolean$1;
}

function classify(value) {
  if (Js_types.test(value, /* String */4)) {
    return /* String */Block.__(0, [value]);
  } else {
    return /* Boolean */Block.__(1, [value]);
  }
}

var StringBooleanUnion = {
  string: string,
  $$boolean: $$boolean,
  classify: classify
};

function contentType(filename) {
  var contentType$1 = classify(MimeTypes.contentType(filename));
  if (contentType$1.tag) {
    return ;
  } else {
    return contentType$1[0];
  }
}

exports.StringBooleanUnion = StringBooleanUnion;
exports.contentType = contentType;
/* mime-types Not a pure module */
