// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Squel = require("squel");

var Select = { };

var Block = { };

function makeInsertOrIgnore(param) {
  return Squel.insert(undefined, [
              new (Squel.cls.StringBlock)(undefined, "INSERT OR IGNORE"),
              new (Squel.cls.IntoTableBlock)(),
              new (Squel.cls.InsertFieldValueBlock)()
            ]);
}

var Insert = {
  makeInsertOrIgnore: makeInsertOrIgnore
};

exports.Select = Select;
exports.Block = Block;
exports.Insert = Insert;
/* squel Not a pure module */
