// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Markdown from "../components/Markdown.bs.js";

function buildHeadingRoute(id) {
  return {
          TAG: /* About */2,
          id: id
        };
}

function AboutPage(Props) {
  var param = Props.data;
  return React.createElement(Markdown.make, {
              buildHeadingRoute: buildHeadingRoute,
              text: param.text
            });
}

var make = AboutPage;

export {
  buildHeadingRoute ,
  make ,
  
}
/* react Not a pure module */
