// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Markdown from "../components/Markdown.bs.js";

function AboutPage(Props) {
  var param = Props.data;
  return React.createElement(Markdown.make, {
              text: param.text
            });
}

var make = AboutPage;

export {
  make ,
  
}
/* react Not a pure module */
