// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function EntryPage(Props) {
  var param = Props.data;
  return React.createElement("div", undefined, React.createElement("div", undefined, param.title), React.createElement("div", undefined, param.text));
}

var make = EntryPage;

exports.make = make;
/* react Not a pure module */
