// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as Utils from "../../Utils.bs.js";
import * as React from "react";
import * as Heading from "../components/Heading.bs.js";
import * as Markdown from "../components/Markdown.bs.js";
import * as RouteLink from "../components/RouteLink.bs.js";
import * as Timestamp from "../components/Timestamp.bs.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";
import * as Relude_Function from "relude/src/Relude_Function.bs.js";

var className = Curry._1(Css.style, /* :: */[
      Css.marginBottom(Css.rem(1.6)),
      /* :: */[
        Css.paddingBottom(Css.rem(0.3)),
        /* :: */[
          Relude_Function.uncurry3(Css.borderBottom, Style.border),
          /* [] */0
        ]
      ]
    ]);

function EntryPage$Header(Props) {
  var children = Props.children;
  return React.createElement("header", {
              className: className
            }, children);
}

var Header = {
  className: className,
  make: EntryPage$Header
};

var className$1 = Curry._1(Css.style, /* :: */[
      Css.fontSize(Css.rem(1.75)),
      /* :: */[
        Css.marginBottom(Css.rem(1.0)),
        /* :: */[
          Css.textAlign(Css.center),
          /* :: */[
            Style.desktopMediaQuery(/* :: */[
                  Css.textAlign(Css.unset),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

function EntryPage$StyledHeading(Props) {
  var children = Props.children;
  return React.createElement(Heading.make, {
              className: className$1,
              children: children
            });
}

var StyledHeading = {
  className: className$1,
  make: EntryPage$StyledHeading
};

var className$2 = Curry._1(Css.style, /* :: */[
      Css.display(Css.inlineBlock),
      /* :: */[
        Css.fontStyle(Css.italic),
        /* :: */[
          Css.margin2(Css.zero, Css.rem(0.6)),
          /* :: */[
            Css.firstOfType(/* :: */[
                  Css.margin(Css.zero),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

function EntryPage$TagItem(Props) {
  var tag = Props.tag;
  var route_000 = /* slug */Curry._1(Utils.slug(undefined), tag);
  var route = /* TagSearch */Block.__(1, [
      route_000,
      /* page */1
    ]);
  return React.createElement("li", {
              className: className$2
            }, React.createElement(RouteLink.make, {
                  route: route,
                  children: tag
                }));
}

var TagItem = {
  className: className$2,
  make: EntryPage$TagItem
};

var className$3 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexWrap(Css.wrap),
        /* :: */[
          Css.margin(Css.zero),
          /* :: */[
            Css.padding(Css.zero),
            /* [] */0
          ]
        ]
      ]
    ]);

function EntryPage$TagList(Props) {
  var tags = Props.tags;
  var tags$1 = Relude_List.map((function (tag) {
            return React.createElement(EntryPage$TagItem, {
                        tag: tag,
                        key: tag
                      });
          }))(tags);
  return React.createElement("ul", {
              className: className$3
            }, Utils.reactList(tags$1));
}

var TagList = {
  className: className$3,
  make: EntryPage$TagList
};

var className$4 = Curry._1(Css.style, /* :: */[
      Css.display(Css.block),
      /* :: */[
        Css.marginBottom(Css.rem(0.3)),
        /* [] */0
      ]
    ]);

function EntryPage$StyledTimestamp(Props) {
  var date = Props.date;
  return React.createElement(Timestamp.make, {
              className: className$4,
              date: date
            });
}

var StyledTimestamp = {
  className: className$4,
  make: EntryPage$StyledTimestamp
};

function EntryPage(Props) {
  var param = Props.data;
  return React.createElement(React.Fragment, undefined, React.createElement(EntryPage$Header, {
                  children: null
                }, React.createElement(EntryPage$StyledHeading, {
                      children: param.title
                    }), React.createElement(EntryPage$StyledTimestamp, {
                      date: param.date
                    }), React.createElement(EntryPage$TagList, {
                      tags: param.tags
                    })), React.createElement("section", undefined, React.createElement(Markdown.make, {
                      text: param.text
                    })));
}

var make = EntryPage;

export {
  Header ,
  StyledHeading ,
  TagItem ,
  TagList ,
  StyledTimestamp ,
  make ,
  
}
/* className Not a pure module */
