// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Relude_List = require("relude/src/Relude_List.bs.js");

function IndexPage(Props) {
  var param = Props.data;
  var entries = Relude_List.toArray(Relude_List.map((function (entry) {
                return React.createElement("div", {
                            key: entry.title
                          }, entry.title);
              }))(param.entries));
  return React.createElement("div", undefined, React.createElement("div", undefined, "page " + (String(param.page) + "")), React.createElement("div", undefined, "total " + (String(param.total) + "")), React.createElement("div", undefined, entries));
}

var make = IndexPage;

exports.make = make;
/* react Not a pure module */
