// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as $$Date from "../../bindings/Date.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as Utils from "../../Utils.bs.js";
import * as React from "react";
import * as Heading from "../components/Heading.bs.js";
import * as RouteLink from "../components/RouteLink.bs.js";
import * as Timestamp from "../components/Timestamp.bs.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";
import * as Relude_Function from "relude/src/Relude_Function.bs.js";

var className = Curry._1(Css.merge, /* :: */[
      Style.smallCapsClassName,
      /* :: */[
        Curry._1(Css.style, /* :: */[
              Css.fontSize(Css.rem(1.5)),
              /* :: */[
                Css.marginBottom(Css.zero),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

function IndexPage$NoMarginHeading(Props) {
  var children = Props.children;
  return React.createElement(Heading.make, {
              className: className,
              children: children
            });
}

var NoMarginHeading = {
  className: className,
  make: IndexPage$NoMarginHeading
};

var className$1 = Curry._1(Css.style, /* :: */[
      Relude_Function.uncurry3(Css.borderBottom, Style.border),
      /* :: */[
        Css.paddingBottom(Css.rem(0.2)),
        /* :: */[
          Css.margin2(Css.rem(0.5), Css.zero),
          /* :: */[
            Style.desktopMediaQuery(/* :: */[
                  Css.margin2(Css.rem(1.0), Css.zero),
                  /* [] */0
                ]),
            /* :: */[
              Css.firstChild(/* :: */[
                    Css.marginTop(Css.zero),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

function IndexPage$Article(Props) {
  var children = Props.children;
  return React.createElement("article", {
              className: className$1
            }, children);
}

var Article = {
  className: className$1,
  make: IndexPage$Article
};

function IndexPage(Props) {
  var param = Props.data;
  return Relude_List.toArray(Relude_List.map((function (entry) {
                      var route_000 = /* year */entry.date.getFullYear();
                      var route_001 = /* month */$$Date.getMonth(entry.date);
                      var route_002 = /* day */entry.date.getDate();
                      var route_003 = /* slug */Curry._1(Utils.slug(undefined), entry.title);
                      var route = /* Entry */Block.__(2, [
                          route_000,
                          route_001,
                          route_002,
                          route_003
                        ]);
                      return React.createElement(IndexPage$Article, {
                                  children: React.createElement("header", undefined, React.createElement(IndexPage$NoMarginHeading, {
                                            children: React.createElement(RouteLink.make, {
                                                  route: route,
                                                  children: entry.title
                                                })
                                          }), React.createElement(Timestamp.make, {
                                            date: entry.date
                                          })),
                                  key: entry.date.toISOString() + entry.title
                                });
                    }))(param.entries));
}

var make = IndexPage;

export {
  NoMarginHeading ,
  Article ,
  make ,
  
}
/* className Not a pure module */
