// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function NotFoundPage(Props) {
  return React.createElement("div", undefined, "not found");
}

var make = NotFoundPage;

export {
  make ,
  
}
/* react Not a pure module */
