// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function NotFoundPage(Props) {
  return "The requested page could not be found";
}

var make = NotFoundPage;

export {
  make ,
  
}
/* No side effect */
