// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function NotFoundPage(Props) {
  return React.createElement("div", undefined, "not found");
}

var make = NotFoundPage;

exports.make = make;
/* react Not a pure module */
