// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Relude_List from "relude/src/Relude_List.bs.js";

function TagSearchPage(Props) {
  var param = Props.data;
  var entries = Relude_List.toArray(Relude_List.map((function (entry) {
                return React.createElement("div", {
                            key: entry.title
                          }, entry.title);
              }))(param.entries));
  return React.createElement("div", undefined, React.createElement("div", undefined, "tag " + (String(param.tag) + "")), React.createElement("div", undefined, "page " + (String(param.page) + "")), React.createElement("div", undefined, entries));
}

var make = TagSearchPage;

export {
  make ,
  
}
/* react Not a pure module */
