// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BootstrapRebootScss from "bootstrap/scss/bootstrap-reboot.scss";

function Page(Props) {
  var title = Props.title;
  var css = Props.css;
  var param = Props.favicon;
  var children = Props.children;
  return React.createElement("html", {
              lang: "en"
            }, React.createElement("head", undefined, React.createElement("meta", {
                      charSet: "utf-8"
                    }), React.createElement("meta", {
                      content: "width=device-width, initial-scale=1, shrink-to-fit=no",
                      name: "viewport"
                    }), React.createElement("link", {
                      href: param.uri,
                      rel: "icon",
                      type: param.mimeType
                    }), React.createElement("title", undefined, title), React.createElement("style", undefined, BootstrapRebootScss + css)), React.createElement("body", undefined, React.createElement("div", {
                      dangerouslySetInnerHTML: {
                        __html: children
                      }
                    })));
}

var make = Page;

export {
  make ,
  
}
/* react Not a pure module */
