// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Emotion from "../bindings/Emotion.bs.js";
import * as AboutPage from "./pages/AboutPage.bs.js";
import * as EntryPage from "./pages/EntryPage.bs.js";
import * as IndexPage from "./pages/IndexPage.bs.js";
import * as NotFoundPage from "./pages/NotFoundPage.bs.js";
import * as TagSearchPage from "./pages/TagSearchPage.bs.js";
import * as BootstrapRebootScss from "bootstrap/scss/bootstrap-reboot.scss";

function formatTitle(siteName, pageData) {
  if (pageData === undefined) {
    return "Not found | " + (String(siteName) + "");
  }
  switch (pageData.tag | 0) {
    case /* Index */0 :
        return siteName;
    case /* TagSearch */1 :
        return "" + (String(pageData[0].tag) + (" | " + (String(siteName) + "")));
    case /* About */2 :
        return "About | " + (String(siteName) + "");
    case /* Entry */3 :
        return "" + (String(pageData[0].title) + (" | " + (String(siteName) + "")));
    
  }
}

var className = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.minHeight(Css.vh(100.0)),
          /* [] */0
        ]
      ]
    ]);

function Page__Component$Root(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className
            }, children);
}

var Root = {
  className: className,
  make: Page__Component$Root
};

function Page__Component(Props) {
  var siteName = Props.siteName;
  var pageData = Props.pageData;
  var title = formatTitle(siteName, pageData);
  var content;
  if (pageData !== undefined) {
    switch (pageData.tag | 0) {
      case /* Index */0 :
          content = React.createElement(IndexPage.make, {
                data: pageData[0]
              });
          break;
      case /* TagSearch */1 :
          content = React.createElement(TagSearchPage.make, {
                data: pageData[0]
              });
          break;
      case /* About */2 :
          content = React.createElement(AboutPage.make, {
                data: pageData[0]
              });
          break;
      case /* Entry */3 :
          content = React.createElement(EntryPage.make, {
                data: pageData[0]
              });
          break;
      
    }
  } else {
    content = React.createElement(NotFoundPage.make, { });
  }
  return React.createElement(Emotion.Provider.make, {
              children: React.createElement("html", {
                    lang: "en"
                  }, React.createElement("head", undefined, React.createElement("meta", {
                            charSet: "utf-8"
                          }), React.createElement("meta", {
                            content: "width=device-width, initial-scale=1, shrink-to-fit=no",
                            name: "viewport"
                          }), React.createElement("title", undefined, title), React.createElement("style", undefined, BootstrapRebootScss)), React.createElement("body", undefined, React.createElement(Page__Component$Root, {
                            children: content
                          })))
            });
}

var make = Page__Component;

export {
  formatTitle ,
  Root ,
  make ,
  
}
/* className Not a pure module */
