// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Page from "./Page.bs.js";
import * as React from "react";
import * as EmotionServer from "emotion-server";
import * as Server from "react-dom/server";

function render(siteName, pageData) {
  var rendered = EmotionServer.renderStylesToString(Server.renderToString(React.createElement(Page.make, {
                siteName: siteName,
                pageData: pageData
              })));
  return "<!DOCTYPE html>" + rendered;
}

export {
  render ,
  
}
/* Page Not a pure module */
