// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";
import * as Relude_Function from "relude/src/Relude_Function.bs.js";

var desktopColumnWidth = Css.rem(50.0);

function desktopMediaQuery(param) {
  return Css.media("(min-width: 37.5rem)", param);
}

var textColour = Css.rgb(173, 175, 174);

var linkColour = Css.rgb(222, 226, 230);

var border_000 = Css.px(1);

var border_002 = Css.rgb(40, 40, 40);

var border = /* tuple */[
  border_000,
  /* solid */12956715,
  border_002
];

var smallCapsClassName = Curry._1(Css.style, /* :: */[
      Css.fontFamily(/* serif */-97640579),
      /* :: */[
        Css.unsafe("font-variant", "small-caps"),
        /* [] */0
      ]
    ]);

var centredColumnClassName = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.width(Css.pct(100.0)),
        /* :: */[
          Css.media("(min-width: 37.5rem)", /* :: */[
                Css.maxWidth(desktopColumnWidth),
                /* [] */0
              ]),
          /* [] */0
        ]
      ]
    ]);

function combineClassNames(classNames) {
  return Curry._1(Css.merge, Relude_List.mapOption(Relude_Function.identity, classNames));
}

var backgroundColour = Css.black;

var linkHoverColour = Css.white;

export {
  desktopColumnWidth ,
  desktopMediaQuery ,
  backgroundColour ,
  textColour ,
  linkColour ,
  linkHoverColour ,
  border ,
  smallCapsClassName ,
  centredColumnClassName ,
  combineClassNames ,
  
}
/* desktopColumnWidth Not a pure module */
