// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Response from "../Response.bs.js";

function makeResponse(about) {
  return {
          TAG: /* Pure */0,
          _0: $$Response.page(undefined, {
                TAG: /* About */2,
                _0: {
                  text: about
                }
              }, undefined)
        };
}

export {
  makeResponse ,
  
}
/* No side effect */
