// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";

function makeResponse(about) {
  return /* Pure */Block.__(0, [/* Page */Block.__(0, [
                /* data *//* About */Block.__(2, [{
                      text: about
                    }]),
                /* status */200
              ])]);
}

export {
  makeResponse ,
  
}
/* No side effect */
