// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Date from "../bindings/Date.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Utils from "../Utils.bs.js";
import * as $$Response from "../Response.bs.js";
import * as Relude_IO from "relude/src/Relude_IO.bs.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";
import * as Relude_Float from "relude/src/Relude_Float.bs.js";
import * as Relude_Option from "relude/src/Relude_Option.bs.js";

function dayTimestamp(date) {
  return $$Date.make(date.getFullYear(), $$Date.getMonth(date), date.getDate(), undefined, undefined, undefined).getTime();
}

function makeResponse(entries, year, month, day, slug) {
  var timestamp = $$Date.make(year, month, day, undefined, undefined, undefined).getTime();
  return Relude_IO.map((function (entry) {
                return $$Response.page(undefined, {
                            TAG: /* Entry */3,
                            _0: {
                              title: entry.title,
                              date: entry.date,
                              text: entry.text,
                              tags: entry.tags,
                              previous: Relude_Option.map((function (entry) {
                                      return {
                                              title: entry.title,
                                              date: entry.date
                                            };
                                    }), Curry._2(Relude_List.find, (function (entry) {
                                          return dayTimestamp(entry.date) < timestamp;
                                        }), Relude_List.sortBy((function (a, b) {
                                              return Curry._2(Relude_Float.compare, b.date.getTime(), a.date.getTime());
                                            }), entries))),
                              next: Relude_Option.map((function (entry) {
                                      return {
                                              title: entry.title,
                                              date: entry.date
                                            };
                                    }), Curry._2(Relude_List.find, (function (entry) {
                                          return dayTimestamp(entry.date) > timestamp;
                                        }), Relude_List.sortBy((function (a, b) {
                                              return Curry._2(Relude_Float.compare, a.date.getTime(), b.date.getTime());
                                            }), entries)))
                            }
                          }, undefined);
              }), Relude_IO.fromOption((function (prim) {
                    
                  }), Curry._2(Relude_List.find, (function (entry) {
                        if (dayTimestamp(entry.date) === timestamp) {
                          return Utils.slug(entry.title) === slug;
                        } else {
                          return false;
                        }
                      }), entries)));
}

export {
  dayTimestamp ,
  makeResponse ,
  
}
/* Utils Not a pure module */
