// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as $$Response from "../Response.bs.js";
import * as Constants from "../Constants.bs.js";
import * as Relude_IO from "relude/src/Relude_IO.bs.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";
import * as Relude_Float from "relude/src/Relude_Float.bs.js";
import * as Relude_Option from "relude/src/Relude_Option.bs.js";

function makeResponse(entries, page) {
  return Relude_IO.fromOption((function (prim) {
                
              }), Curry._2(Relude_Option.flatMap, (function (param) {
                    return Relude_Option.map((function (pageEntries) {
                                  return $$Response.page(undefined, {
                                              TAG: /* Index */0,
                                              _0: {
                                                page: page,
                                                total: Curry._1(Relude_List.length, entries),
                                                entries: Relude_List.map(function (entry) {
                                                        return {
                                                                title: entry.title,
                                                                date: entry.date,
                                                                text: entry.text
                                                              };
                                                      })(pageEntries)
                                              }
                                            }, undefined);
                                }), Relude_Option.filter(function (pageEntries) {
                                      return Curry._1(Relude_List.length, pageEntries) !== 0;
                                    })(Relude_List.take(Constants.entriesPerPage, param[1])));
                  }), Relude_List.splitAt(Math.imul(page - 1 | 0, Constants.entriesPerPage), Relude_List.sortBy((function (a, b) {
                            return Curry._2(Relude_Float.compare, b.date.getTime(), a.date.getTime());
                          }), entries))));
}

export {
  makeResponse ,
  
}
/* Relude_IO Not a pure module */
