// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";

var response = /* Pure */Block.__(0, [/* Page */Block.__(0, [
        /* data */undefined,
        /* status */404
      ])]);

export {
  response ,
  
}
/* No side effect */
