// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var response = /* Pure */Block.__(0, [/* Page */Block.__(0, [
        /* data */undefined,
        /* status */404
      ])]);

exports.response = response;
/* No side effect */
