// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var MimeTypes = require("../bindings/MimeTypes.bs.js");
var Relude_IO = require("relude/src/Relude_IO.bs.js");
var NodeFS__Stat = require("node-fs-bs/src/NodeFS__Stat.bs.js");
var NodeFS__ReadStream = require("node-fs-bs/src/NodeFS__ReadStream.bs.js");

function makeResponse(directory, filename) {
  var path = Path.join(__dirname, directory, filename);
  return Curry._2(Relude_IO.mapError, (function (prim) {
                
              }), Relude_IO.flatMap((function (param) {
                    var mtime = param.mtime;
                    var size = param.size;
                    return Relude_IO.map((function (stream) {
                                  return /* Stream */Block.__(1, [
                                            /* stream */stream,
                                            /* type_ */MimeTypes.contentType(filename),
                                            /* length */size,
                                            /* modified */mtime
                                          ]);
                                }), NodeFS__ReadStream.make(path));
                  }), NodeFS__Stat.stat(path)));
}

exports.makeResponse = makeResponse;
/* path Not a pure module */
