// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Utils from "../Utils.bs.js";
import * as $$Response from "../Response.bs.js";
import * as Constants from "../Constants.bs.js";
import * as Relude_IO from "relude/src/Relude_IO.bs.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";
import * as Relude_Float from "relude/src/Relude_Float.bs.js";
import * as Relude_Option from "relude/src/Relude_Option.bs.js";

function makeResponse(entries, slug, page) {
  return Relude_IO.fromOption((function (prim) {
                
              }), Curry._2(Relude_Option.flatMap, (function (param) {
                    var tag = param[2];
                    var filteredEntries = param[0];
                    return Relude_Option.map((function (pageEntries) {
                                  return $$Response.page(undefined, {
                                              TAG: /* TagSearch */1,
                                              _0: {
                                                tag: tag,
                                                page: page,
                                                total: Curry._1(Relude_List.length, filteredEntries),
                                                entries: Relude_List.map(function (entry) {
                                                        return {
                                                                title: entry.title,
                                                                date: entry.date,
                                                                text: entry.text
                                                              };
                                                      })(pageEntries)
                                              }
                                            }, undefined);
                                }), Relude_Option.filter(function (pageEntries) {
                                      return Curry._1(Relude_List.length, pageEntries) !== 0;
                                    })(Relude_List.take(Constants.entriesPerPage, param[1])));
                  }), Curry._2(Relude_Option.flatMap, (function (param) {
                        var tag = param[1];
                        var filteredEntries = param[0];
                        return Relude_Option.map((function (param) {
                                      return [
                                              filteredEntries,
                                              param[1],
                                              tag
                                            ];
                                    }), Relude_List.splitAt(Math.imul(page - 1 | 0, Constants.entriesPerPage), Relude_List.sortBy((function (a, b) {
                                              return Curry._2(Relude_Float.compare, b.date.getTime(), a.date.getTime());
                                            }), filteredEntries)));
                      }), Relude_List.foldLeft((function (accumulator, entry) {
                              var tag = Curry._2(Relude_List.find, (function (tag) {
                                      return Utils.slug(tag) === slug;
                                    }), entry.tags);
                              if (tag !== undefined) {
                                if (accumulator !== undefined) {
                                  return [
                                          {
                                            hd: entry,
                                            tl: accumulator[0]
                                          },
                                          tag
                                        ];
                                } else {
                                  return [
                                          {
                                            hd: entry,
                                            tl: /* [] */0
                                          },
                                          tag
                                        ];
                                }
                              } else {
                                return accumulator;
                              }
                            }), undefined)(entries))));
}

export {
  makeResponse ,
  
}
/* Utils Not a pure module */
