// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as $$Response from "../Response.bs.js";
import * as MimeTypes from "mime-types-bs/src/MimeTypes.bs.js";
import * as Relude_IO from "relude/src/Relude_IO.bs.js";
import * as NodeFS__Stat from "node-fs-bs/src/NodeFS__Stat.bs.js";
import * as SanitizeFilename from "sanitize-filename";
import * as NodeFS__ReadStream from "node-fs-bs/src/NodeFS__ReadStream.bs.js";

function makeResponse(directory, filename) {
  var sanitisedFilename = SanitizeFilename(filename);
  var path = Path.join(directory, sanitisedFilename);
  return Curry._2(Relude_IO.mapError, (function (prim) {
                
              }), Relude_IO.flatMap((function (param) {
                    var mtime = param.mtime;
                    var size = param.size;
                    return Relude_IO.map((function (stream) {
                                  return $$Response.stream(MimeTypes.contentType(sanitisedFilename), stream, size, mtime);
                                }), NodeFS__ReadStream.make(path));
                  }), NodeFS__Stat.stat(path)));
}

export {
  makeResponse ,
  
}
/* path Not a pure module */
