// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Relude_IO from "relude/src/Relude_IO.bs.js";
import * as SQLiteRelude from "sqlite-relude/src/SQLiteRelude.bs.js";
import * as Database__Connection from "./Database__Connection.bs.js";

function createAboutPageTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS AboutPage (\n        text TEXT PRIMARY KEY\n    )\n", param);
}

function createEntryTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Entry (\n        json TEXT PRIMARY KEY\n    )\n", param);
}

function createAllTables(param) {
  return Database__Connection.transaction((function (connection) {
                return Relude_IO.flatMap((function (param) {
                              return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Entry (\n        json TEXT PRIMARY KEY\n    )\n", connection);
                            }), SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS AboutPage (\n        text TEXT PRIMARY KEY\n    )\n", connection));
              }), param);
}

export {
  createAboutPageTable ,
  createEntryTable ,
  createAllTables ,
  
}
/* Relude_IO Not a pure module */
