// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Relude_IO from "relude/src/Relude_IO.bs.js";
import * as SQLiteRelude from "sqlite-relude/src/SQLiteRelude.bs.js";
import * as Database__Connection from "./Database__Connection.bs.js";

function createAboutPageTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS AboutPage (\n        text TEXT PRIMARY KEY\n    )\n", param);
}

function createEntryTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Entry (\n        slug TEXT PRIMARY KEY,\n        title TEXT NOT NULL,\n        timestamp INTEGER NOT NULL,\n        text TEXT NOT NULL\n    )\n", param);
}

function createTagTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Tag (\n        slug TEXT PRIMARY KEY,\n        name TEXT NOT NULL\n    )\n", param);
}

function createEntryTagTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS EntryTag (\n        entrySlug TEXT NOT NULL REFERENCES Entry(slug) ON UPDATE CASCADE ON DELETE CASCADE,\n        tagSlug TEXT NOT NULL REFERENCES Tag(slug) ON UPDATE CASCADE ON DELETE CASCADE,\n        PRIMARY KEY (entrySlug, tagSlug)\n    )\n", param);
}

function createAllTables(param) {
  return Database__Connection.transaction((function (connection) {
                return Relude_IO.flatMap((function (param) {
                              return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS EntryTag (\n        entrySlug TEXT NOT NULL REFERENCES Entry(slug) ON UPDATE CASCADE ON DELETE CASCADE,\n        tagSlug TEXT NOT NULL REFERENCES Tag(slug) ON UPDATE CASCADE ON DELETE CASCADE,\n        PRIMARY KEY (entrySlug, tagSlug)\n    )\n", connection);
                            }), Relude_IO.flatMap((function (param) {
                                  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Tag (\n        slug TEXT PRIMARY KEY,\n        name TEXT NOT NULL\n    )\n", connection);
                                }), Relude_IO.flatMap((function (param) {
                                      return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Entry (\n        slug TEXT PRIMARY KEY,\n        title TEXT NOT NULL,\n        timestamp INTEGER NOT NULL,\n        text TEXT NOT NULL\n    )\n", connection);
                                    }), SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS AboutPage (\n        text TEXT PRIMARY KEY\n    )\n", connection))));
              }), param);
}

export {
  createAboutPageTable ,
  createEntryTable ,
  createTagTable ,
  createEntryTagTable ,
  createAllTables ,
  
}
/* Relude_IO Not a pure module */
