// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Relude_IO = require("relude/src/Relude_IO.bs.js");
var SQLiteRelude = require("sqlite-relude/src/SQLiteRelude.bs.js");
var Database__Connection = require("./Database__Connection.bs.js");

function createAboutPageTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS AboutPage (\n        text TEXT PRIMARY KEY\n    )\n", param);
}

function createEntryTable(param) {
  return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Entry (\n        json TEXT PRIMARY KEY\n    )\n", param);
}

function createAllTables(param) {
  return Database__Connection.transaction((function (connection) {
                return Relude_IO.flatMap((function (param) {
                              return SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS Entry (\n        json TEXT PRIMARY KEY\n    )\n", connection);
                            }), SQLiteRelude.run("\n    CREATE TABLE IF NOT EXISTS AboutPage (\n        text TEXT PRIMARY KEY\n    )\n", connection));
              }), param);
}

exports.createAboutPageTable = createAboutPageTable;
exports.createEntryTable = createEntryTable;
exports.createAllTables = createAllTables;
/* Relude_IO Not a pure module */
