// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Package from "./bindings/Package.bs.js";
import * as ArgParse from "./bindings/ArgParse.bs.js";

function parseArguments(param) {
  var parser = ArgParse.make(Package.json.version, Package.json.name);
  ArgParse.addArgument("--site-name", "siteName", parser);
  ArgParse.addArgument("--entries-directory", "entriesDirectory", parser);
  ArgParse.addArgument("--about-path", "aboutPath", parser);
  return parser.parseArgs();
}

export {
  parseArguments ,
  
}
/* Package Not a pure module */
