// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var CLI = require("./CLI.bs.js");
var Server = require("./Server.bs.js");

function main(param) {
  var match = CLI.parseArguments(undefined);
  return Server.listen(Server.make(match.siteName));
}

main(undefined);

exports.main = main;
/*  Not a pure module */
