// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Date from "./bindings/Date.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Utils from "./Utils.bs.js";

function toRoute(pageData) {
  switch (pageData.tag | 0) {
    case /* Index */0 :
        return /* Index */Block.__(0, [/* page */pageData[0].page]);
    case /* TagSearch */1 :
        var match = pageData[0];
        return /* TagSearch */Block.__(1, [
                  /* slug */Utils.slug(match.tag),
                  /* page */match.page
                ]);
    case /* About */2 :
        return /* About */Block.__(2, [/* id */undefined]);
    case /* Entry */3 :
        var match$1 = pageData[0];
        var date = match$1.date;
        return /* Entry */Block.__(3, [
                  /* year */date.getFullYear(),
                  /* month */$$Date.getMonth(date),
                  /* day */date.getDate(),
                  /* slug */Utils.slug(match$1.title),
                  /* id */undefined
                ]);
    
  }
}

export {
  toRoute ,
  
}
/* Utils Not a pure module */
