// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Date from "./bindings/Date.bs.js";
import * as Utils from "./Utils.bs.js";

function toRoute(pageData) {
  switch (pageData.TAG | 0) {
    case /* Index */0 :
        return {
                TAG: /* Index */0,
                page: pageData._0.page
              };
    case /* TagSearch */1 :
        var match = pageData._0;
        return {
                TAG: /* TagSearch */1,
                slug: Utils.slug(match.tag),
                page: match.page
              };
    case /* About */2 :
        return {
                TAG: /* About */2,
                id: undefined
              };
    case /* Entry */3 :
        var match$1 = pageData._0;
        var date = match$1.date;
        return {
                TAG: /* Entry */3,
                year: date.getFullYear(),
                month: $$Date.getMonth(date),
                day: date.getDate(),
                slug: Utils.slug(match$1.title),
                id: undefined
              };
    
  }
}

export {
  toRoute ,
  
}
/* Utils Not a pure module */
