// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as App from "./views/App.bs.js";
import * as Page from "./views/Page.bs.js";
import * as Style from "./views/Style.bs.js";
import * as React from "react";
import * as EmotionServer from "emotion-server";
import * as Server from "react-dom/server";

function render(siteName, favicon, pageData) {
  Style.registerGlobalStyles(undefined);
  var renderedApp = Server.renderToString(React.createElement(App.make, {
            siteName: siteName,
            pageData: pageData
          }));
  var match = EmotionServer.extractCritical(renderedApp);
  var title;
  if (pageData !== undefined) {
    switch (pageData.TAG | 0) {
      case /* Index */0 :
          title = siteName;
          break;
      case /* TagSearch */1 :
          title = "" + pageData._0.tag + " | " + siteName;
          break;
      case /* About */2 :
          title = "About | " + siteName;
          break;
      case /* Entry */3 :
          title = "" + pageData._0.title + " | " + siteName;
          break;
      
    }
  } else {
    title = "Not found | " + siteName;
  }
  var renderedPage = Server.renderToString(React.createElement(Page.make, {
            title: title,
            css: match.css,
            favicon: favicon,
            children: match.html
          }));
  return "<!DOCTYPE html>" + renderedPage;
}

export {
  render ,
  
}
/* App Not a pure module */
