// Generated by ReScript, PLEASE EDIT WITH CARE


function page(statusOpt, state, param) {
  var status = statusOpt !== undefined ? statusOpt : 200;
  return {
          TAG: /* Page */0,
          state: state,
          status: status
        };
}

function stream(type_, stream$1, length, modified) {
  return {
          TAG: /* Stream */1,
          stream: stream$1,
          type_: type_,
          length: length,
          modified: modified
        };
}

var notFound = {
  TAG: /* Page */0,
  state: undefined,
  status: 404
};

export {
  notFound ,
  page ,
  stream ,
  
}
/* No side effect */
