// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var notFound = /* Page */Block.__(0, [
    /* data */undefined,
    /* status */400
  ]);

exports.notFound = notFound;
/* No side effect */
