// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";

var notFound = /* Page */Block.__(0, [
    /* data */undefined,
    /* status */400
  ]);

export {
  notFound ,
  
}
/* No side effect */
