// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Slugify from "slugify-bs/src/Slugify.bs.js";

function slug(param) {
  return Curry._3(Slugify.slugify, "-", param, true);
}

export {
  slug ,
  
}
/* Slugify Not a pure module */
