// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";
import * as RouterLink from "./RouterLink.bs.js";

var className = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.flexGrow(1.0),
          /* [] */0
        ]
      ]
    ]);

function Content$Outer(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className
            }, children);
}

var Outer = {
  className: className,
  make: Content$Outer
};

var className$1 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.justifyContent(Css.center),
        /* :: */[
          Css.backgroundColor(Style.grey7),
          /* :: */[
            Css.color(Style.grey2),
            /* [] */0
          ]
        ]
      ]
    ]);

function Content$Nav(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className$1
            }, children);
}

var className$2 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.justifyContent(Css.spaceBetween),
        /* :: */[
          Css.width(Css.pct(100.0)),
          /* :: */[
            Style.desktopMediaQuery(/* :: */[
                  Style.desktopColumnWidth,
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

function Content$Nav$Inner(Props) {
  var children = Props.children;
  return React.createElement("nav", {
              className: className$2
            }, children);
}

var className$3 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.alignItems(Css.center),
        /* [] */0
      ]
    ]);

function Content$Nav$Inner$RightGroup(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className$3
            }, children);
}

var RightGroup = {
  className: className$3,
  make: Content$Nav$Inner$RightGroup
};

var Inner = {
  className: className$2,
  make: Content$Nav$Inner,
  RightGroup: RightGroup
};

var className$4 = Curry._1(Css.style, /* :: */[
      Css.fontSize(Css.rem(1.125)),
      /* :: */[
        Css.padding2(Css.rem(0.25), Css.rem(0.625)),
        /* :: */[
          Css.color(Style.grey2),
          /* :: */[
            Css.hover(/* :: */[
                  Css.backgroundColor(Style.grey9),
                  /* :: */[
                    Css.color(Css.white),
                    /* :: */[
                      Css.textDecoration(Css.none),
                      /* [] */0
                    ]
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

function Content$Nav$Link(Props) {
  var route = Props.route;
  var children = Props.children;
  return React.createElement(RouterLink.make, {
              route: route,
              className: className$4,
              children: children
            });
}

var Link = {
  className: className$4,
  make: Content$Nav$Link
};

var Nav = {
  className: className$1,
  make: Content$Nav,
  Inner: Inner,
  Link: Link
};

var className$5 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.flexGrow(1.0),
          /* :: */[
            Css.alignItems(Css.center),
            /* :: */[
              Css.backgroundColor(Style.grey2),
              /* :: */[
                Css.color(Style.grey7),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

function Content$Main(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className$5
            }, children);
}

var className$6 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.width(Css.pct(100.0)),
          /* :: */[
            Style.desktopMediaQuery(/* :: */[
                  Style.desktopColumnWidth,
                  /* [] */0
                ]),
            /* :: */[
              Css.border(Css.px(1), Css.solid, Style.lightBorderColour),
              /* :: */[
                Css.backgroundColor(Style.grey1),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

function Content$Main$Inner(Props) {
  var children = Props.children;
  return React.createElement("main", {
              className: className$6
            }, children);
}

var Inner$1 = {
  className: className$6,
  make: Content$Main$Inner
};

var Main = {
  className: className$5,
  make: Content$Main,
  Inner: Inner$1
};

function Content(Props) {
  var siteName = Props.siteName;
  var children = Props.children;
  return React.createElement(Content$Outer, {
              children: null
            }, React.createElement(Content$Nav, {
                  children: React.createElement(Content$Nav$Inner, {
                        children: null
                      }, React.createElement(Content$Nav$Link, {
                            route: /* Index */Block.__(0, [/* page */1]),
                            children: siteName
                          }), React.createElement(Content$Nav$Inner$RightGroup, {
                            children: React.createElement(Content$Nav$Link, {
                                  route: /* About */0,
                                  children: "about"
                                })
                          }))
                }), React.createElement(Content$Main, {
                  children: React.createElement(Content$Main$Inner, {
                        children: children
                      })
                }));
}

var make = Content;

export {
  Outer ,
  Nav ,
  Main ,
  make ,
  
}
/* className Not a pure module */
