// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";

var className = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexGrow(1.0),
        /* :: */[
          Css.justifyContent(Css.center),
          /* :: */[
            Css.margin2(Css.zero, Css.rem(0.5)),
            /* [] */0
          ]
        ]
      ]
    ]);

function Content$Container(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className
            }, children);
}

var Container = {
  className: className,
  make: Content$Container
};

var className$1 = Curry._1(Css.merge, /* :: */[
      Style.centredColumnClassName,
      /* :: */[
        Curry._1(Css.style, /* :: */[
              Css.flexDirection(Css.column),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

function Content$Main(Props) {
  var children = Props.children;
  return React.createElement("main", {
              className: className$1
            }, children);
}

var Main = {
  className: className$1,
  make: Content$Main
};

function Content(Props) {
  var children = Props.children;
  return React.createElement(Content$Container, {
              children: React.createElement(Content$Main, {
                    children: children
                  })
            });
}

var make = Content;

export {
  Container ,
  Main ,
  make ,
  
}
/* className Not a pure module */
