// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PrismLight from "react-syntax-highlighter/dist/esm/prism-light";
import * as Tsx from "react-syntax-highlighter/dist/esm/languages/prism/tsx";
import * as Bash from "react-syntax-highlighter/dist/esm/languages/prism/bash";
import * as Json from "react-syntax-highlighter/dist/esm/languages/prism/json";
import * as Tomorrow from "react-syntax-highlighter/dist/esm/styles/prism/tomorrow";
import * as Python from "react-syntax-highlighter/dist/esm/languages/prism/python";
import * as Reason from "react-syntax-highlighter/dist/esm/languages/prism/reason";
import * as Javascript from "react-syntax-highlighter/dist/esm/languages/prism/javascript";
import * as Typescript from "react-syntax-highlighter/dist/esm/languages/prism/typescript";

function registerStyles(param) {
  PrismLight.default.registerLanguage("bash", Bash);
  PrismLight.default.registerLanguage("javascript", Javascript);
  PrismLight.default.registerLanguage("json", Json);
  PrismLight.default.registerLanguage("python", Python);
  PrismLight.default.registerLanguage("reason", Reason);
  PrismLight.default.registerLanguage("typescript", Typescript);
  PrismLight.default.registerLanguage("tsx", Tsx);
  
}

function HighlightedCode(Props) {
  var language = Props.language;
  var text = Props.text;
  return React.createElement(PrismLight, {
              language: language,
              style: Tomorrow,
              children: text
            });
}

var make = HighlightedCode;

export {
  registerStyles ,
  make ,
  
}
/* react Not a pure module */
