// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as PrismLight from "react-syntax-highlighter/dist/esm/prism-light";
import * as Tsx from "react-syntax-highlighter/dist/esm/languages/prism/tsx";
import * as Bash from "react-syntax-highlighter/dist/esm/languages/prism/bash";
import * as Json from "react-syntax-highlighter/dist/esm/languages/prism/json";
import * as Tomorrow from "react-syntax-highlighter/dist/esm/styles/prism/tomorrow";
import * as Python from "react-syntax-highlighter/dist/esm/languages/prism/python";
import * as Reason from "react-syntax-highlighter/dist/esm/languages/prism/reason";
import * as Javascript from "react-syntax-highlighter/dist/esm/languages/prism/javascript";
import * as Typescript from "react-syntax-highlighter/dist/esm/languages/prism/typescript";

function registerStyles(param) {
  PrismLight.default.registerLanguage("bash", Bash.default);
  PrismLight.default.registerLanguage("javascript", Javascript.default);
  PrismLight.default.registerLanguage("json", Json.default);
  PrismLight.default.registerLanguage("python", Python.default);
  PrismLight.default.registerLanguage("reason", Reason.default);
  PrismLight.default.registerLanguage("typescript", Typescript.default);
  PrismLight.default.registerLanguage("tsx", Tsx.default);
  
}

var className = Curry._1(Css.style, /* :: */[
      Css.fontSize(Css.rem(0.8)),
      /* :: */[
        Css.important(Css.marginBottom(Css.rem(1.0))),
        /* [] */0
      ]
    ]);

function HighlightedCode(Props) {
  var language = Props.language;
  var text = Props.text;
  return React.createElement(PrismLight.default, {
              className: className,
              language: language,
              style: Tomorrow.default,
              children: text
            });
}

var make = HighlightedCode;

export {
  registerStyles ,
  className ,
  make ,
  
}
/* className Not a pure module */
