// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";

var hoverStyles_000 = Css.textDecoration(Css.none);

var hoverStyles_001 = /* :: */[
  Css.color(Style.linkHoverColour),
  /* [] */0
];

var hoverStyles = /* :: */[
  hoverStyles_000,
  hoverStyles_001
];

var baseClassName = Curry._1(Css.style, /* :: */[
      Css.color(Style.linkColour),
      /* :: */[
        Css.hover(hoverStyles),
        /* [] */0
      ]
    ]);

var activeClassName = Curry._1(Css.style, hoverStyles);

function Link(Props) {
  var url = Props.url;
  var activeOpt = Props.active;
  var className = Props.className;
  var children = Props.children;
  var active = activeOpt !== undefined ? activeOpt : false;
  var className$1 = Style.combineClassNames(/* :: */[
        baseClassName,
        /* :: */[
          className,
          /* :: */[
            active ? activeClassName : undefined,
            /* [] */0
          ]
        ]
      ]);
  return React.createElement("a", {
              className: className$1,
              href: url
            }, children);
}

var make = Link;

export {
  hoverStyles ,
  baseClassName ,
  activeClassName ,
  make ,
  
}
/* hoverStyles Not a pure module */
