// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";

var hoverStyles_0 = Css.textDecoration(Css.none);

var hoverStyles_1 = {
  hd: Css.color(Style.linkHoverColour),
  tl: /* [] */0
};

var hoverStyles = {
  hd: hoverStyles_0,
  tl: hoverStyles_1
};

var baseClassName = Curry._1(Css.style, {
      hd: Css.color(Style.linkColour),
      tl: {
        hd: Css.hover(hoverStyles),
        tl: /* [] */0
      }
    });

var activeClassName = Curry._1(Css.style, hoverStyles);

function Link(Props) {
  var url = Props.url;
  var activeOpt = Props.active;
  var className = Props.className;
  var children = Props.children;
  var active = activeOpt !== undefined ? activeOpt : false;
  var className$1 = Style.combineClassNames({
        hd: baseClassName,
        tl: {
          hd: className,
          tl: {
            hd: active ? activeClassName : undefined,
            tl: /* [] */0
          }
        }
      });
  return React.createElement("a", {
              className: className$1,
              href: url
            }, children);
}

var make = Link;

export {
  hoverStyles ,
  baseClassName ,
  activeClassName ,
  make ,
  
}
/* hoverStyles Not a pure module */
