// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Link from "./Link.bs.js";
import * as React from "react";
import * as Heading from "./Heading.bs.js";
import * as Spoiler from "./Spoiler.bs.js";
import * as Paragraph from "./Paragraph.bs.js";
import * as ReactMarkdown from "react-markdown";

function Markdown$HTMLElement(Props) {
  var tag = Props.tag;
  var children = Props.children;
  if (tag === "spoiler") {
    return React.createElement(Spoiler.make, {
                children: children
              });
  } else {
    return React.createElement(tag, undefined, children);
  }
}

var $$HTMLElement = {
  make: Markdown$HTMLElement
};

function renderers_virtualHtml(param) {
  return React.createElement(Markdown$HTMLElement, {
              tag: param.tag,
              children: param.children
            });
}

function renderers_heading(param) {
  return React.createElement(Heading.make, {
              level: param.level,
              children: param.children
            });
}

function renderers_paragraph(param) {
  return React.createElement(Paragraph.make, {
              children: param.children
            });
}

function renderers_link(param) {
  return React.createElement(Link.make, {
              url: param.href,
              children: param.children
            });
}

var renderers = {
  virtualHtml: renderers_virtualHtml,
  heading: renderers_heading,
  paragraph: renderers_paragraph,
  link: renderers_link
};

function Markdown(Props) {
  var text = Props.text;
  return React.createElement(ReactMarkdown, {
              source: text,
              escapeHtml: false,
              renderers: renderers
            });
}

var make = Markdown;

export {
  $$HTMLElement ,
  renderers ,
  make ,
  
}
/* Link Not a pure module */
