// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";
import * as RouteLink from "./RouteLink.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Relude_Function from "relude/src/Relude_Function.bs.js";

var className = Curry._1(Css.style, /* :: */[
      Css.marginRight(Css.auto),
      /* :: */[
        Css.fontSize(Css.rem(1.125)),
        /* :: */[
          Css.color(Style.linkHoverColour),
          /* [] */0
        ]
      ]
    ]);

function Nav$HomeLink(Props) {
  var children = Props.children;
  return React.createElement(RouteLink.make, {
              route: /* Index */Block.__(0, [/* page */1]),
              className: className,
              children: children
            });
}

var HomeLink = {
  className: className,
  make: Nav$HomeLink
};

var className$1 = Curry._1(Css.merge, /* :: */[
      Style.centredColumnClassName,
      /* :: */[
        Curry._1(Css.style, /* :: */[
              Css.alignItems(Css.center),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

function Nav$Container(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className$1
            }, children);
}

var Container = {
  className: className$1,
  make: Nav$Container
};

var className$2 = Curry._1(Css.merge, /* :: */[
      Style.smallCapsClassName,
      /* :: */[
        Curry._1(Css.style, /* :: */[
              Css.display(Css.flexBox),
              /* :: */[
                Css.justifyContent(Css.center),
                /* :: */[
                  Css.padding2(Css.rem(0.5), Css.zero),
                  /* :: */[
                    Css.marginBottom(Css.rem(1.6)),
                    /* :: */[
                      Relude_Function.uncurry3(Css.borderBottom, Style.border),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]),
        /* [] */0
      ]
    ]);

function Nav(Props) {
  var siteName = Props.siteName;
  var activeRoute = Props.activeRoute;
  var tmp = {
    route: /* About */0,
    children: "About"
  };
  if (activeRoute !== undefined) {
    tmp.activeRoute = Caml_option.valFromOption(activeRoute);
  }
  return React.createElement("nav", {
              className: className$2
            }, React.createElement(Nav$Container, {
                  children: null
                }, React.createElement(Nav$HomeLink, {
                      children: siteName
                    }), React.createElement(RouteLink.make, tmp)));
}

var make = Nav;

export {
  HomeLink ,
  Container ,
  className$2 as className,
  make ,
  
}
/* className Not a pure module */
