// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";
import * as RouteLink from "./RouteLink.bs.js";

var baseClassName = Curry._1(Css.style, /* :: */[
      Css.padding2(Css.rem(0.5), Css.rem(0.625)),
      /* [] */0
    ]);

function Nav$Link(Props) {
  var className = Props.className;
  var route = Props.route;
  var activeRoute = Props.activeRoute;
  var children = Props.children;
  var className$1 = Style.combineClassNames(/* :: */[
        baseClassName,
        /* :: */[
          className,
          /* [] */0
        ]
      ]);
  return React.createElement(RouteLink.make, {
              route: route,
              activeRoute: activeRoute,
              className: className$1,
              children: children
            });
}

var Link = {
  baseClassName: baseClassName,
  make: Nav$Link
};

var className = Curry._1(Css.style, /* :: */[
      Css.marginRight(Css.auto),
      /* :: */[
        Css.fontSize(Css.rem(1.125)),
        /* :: */[
          Css.color(Style.linkHoverColour),
          /* [] */0
        ]
      ]
    ]);

function Nav$HomeLink(Props) {
  var activeRoute = Props.activeRoute;
  var children = Props.children;
  return React.createElement(Nav$Link, {
              className: className,
              route: /* Index */Block.__(0, [/* page */1]),
              activeRoute: activeRoute,
              children: children
            });
}

var HomeLink = {
  className: className,
  make: Nav$HomeLink
};

var className$1 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.alignItems(Css.center),
        /* :: */[
          Css.width(Css.pct(100.0)),
          /* :: */[
            Style.desktopMediaQuery(/* :: */[
                  Css.maxWidth(Style.desktopColumnWidth),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

function Nav$Container(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: className$1
            }, children);
}

var Container = {
  className: className$1,
  make: Nav$Container
};

var className$2 = Curry._1(Css.style, /* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.justifyContent(Css.center),
        /* :: */[
          Style.border,
          /* :: */[
            Css.fontFamily(/* serif */-97640579),
            /* :: */[
              Css.fontVariant(/* smallCaps */-386684792),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

function Nav(Props) {
  var siteName = Props.siteName;
  var activeRoute = Props.activeRoute;
  return React.createElement("nav", {
              className: className$2
            }, React.createElement(Nav$Container, {
                  children: null
                }, React.createElement(Nav$HomeLink, {
                      activeRoute: activeRoute,
                      children: siteName
                    }), React.createElement(Nav$Link, {
                      route: /* About */0,
                      activeRoute: activeRoute,
                      children: "About"
                    })));
}

var make = Nav;

export {
  Link ,
  HomeLink ,
  Container ,
  className$2 as className,
  make ,
  
}
/* baseClassName Not a pure module */
