// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";
import * as Router from "../../Router.bs.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Relude_Option from "relude/src/Relude_Option.bs.js";

var hoverStyles_000 = Css.textDecoration(Css.none);

var hoverStyles_001 = /* :: */[
  Css.color(Style.linkHoverColour),
  /* [] */0
];

var hoverStyles = /* :: */[
  hoverStyles_000,
  hoverStyles_001
];

var baseClassName = Curry._1(Css.style, /* :: */[
      Css.color(Style.linkColour),
      /* :: */[
        Css.hover(hoverStyles),
        /* [] */0
      ]
    ]);

var activeClassName = Curry._1(Css.style, hoverStyles);

function RouteLink(Props) {
  var route = Props.route;
  var activeRoute = Props.activeRoute;
  var className = Props.className;
  var children = Props.children;
  var className$1 = Style.combineClassNames(/* :: */[
        baseClassName,
        /* :: */[
          className,
          /* :: */[
            Relude_Option.map((function (param) {
                    return activeClassName;
                  }), Relude_Option.filter((function (activeRoute) {
                          return Caml_obj.caml_equal(route, activeRoute);
                        }))(activeRoute)),
            /* [] */0
          ]
        ]
      ]);
  var href = Router.build(route);
  return React.createElement("a", {
              className: className$1,
              href: href
            }, children);
}

var make = RouteLink;

export {
  hoverStyles ,
  baseClassName ,
  activeClassName ,
  make ,
  
}
/* hoverStyles Not a pure module */
