// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./Link.bs.js";
import * as Route from "../../Route.bs.js";
import * as React from "react";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function RouteLink(Props) {
  var route = Props.route;
  var activeRoute = Props.activeRoute;
  var className = Props.className;
  var children = Props.children;
  var url = Route.toURL(route);
  var tmp = {
    url: url,
    active: Caml_obj.caml_equal(route, activeRoute),
    children: children
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement(Link.make, tmp);
}

var make = RouteLink;

export {
  make ,
  
}
/* Link Not a pure module */
