// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "../../Router.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function RouterLink(Props) {
  var route = Props.route;
  var className = Props.className;
  var children = Props.children;
  var href = Router.build(route);
  var tmp = {
    href: href
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("a", tmp, children);
}

var make = RouterLink;

export {
  make ,
  
}
/* react Not a pure module */
