// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Router = require("../../Router.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function RouterLink(Props) {
  var route = Props.route;
  var className = Props.className;
  var children = Props.children;
  var href = Router.build(route);
  var tmp = {
    href: href
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("a", tmp, children);
}

var make = RouterLink;

exports.make = make;
/* react Not a pure module */
