// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";
import * as Router from "../../Router.bs.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

var baseClassName = Curry._1(Css.style, /* :: */[
      Css.textDecoration(Css.none),
      /* :: */[
        Css.color(Style.linkColour),
        /* :: */[
          Css.hover(/* :: */[
                Css.color(Style.linkHoverColour),
                /* [] */0
              ]),
          /* [] */0
        ]
      ]
    ]);

function RouteLink(Props) {
  var route = Props.route;
  var activeRoute = Props.activeRoute;
  var className = Props.className;
  var activeClassName = Props.activeClassName;
  var children = Props.children;
  var activeClassName$1 = activeRoute !== undefined && activeClassName !== undefined && Caml_obj.caml_equal(route, activeRoute) ? activeClassName : undefined;
  var className$1 = Style.combineClassNames(/* :: */[
        baseClassName,
        /* :: */[
          className,
          /* :: */[
            activeClassName$1,
            /* [] */0
          ]
        ]
      ]);
  var href = Router.build(route);
  return React.createElement("a", {
              className: className$1,
              href: href
            }, children);
}

var make = RouteLink;

export {
  baseClassName ,
  make ,
  
}
/* baseClassName Not a pure module */
