// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

var className = Curry._1(Css.style, /* :: */[
      Css.backgroundColor(Css.black),
      /* :: */[
        Css.color(Css.black),
        /* :: */[
          Css.hover(/* :: */[
                Css.color(Css.white),
                /* [] */0
              ]),
          /* [] */0
        ]
      ]
    ]);

function Spoiler(Props) {
  var children = Props.children;
  return React.createElement("span", {
              className: className
            }, children);
}

var make = Spoiler;

export {
  className ,
  make ,
  
}
/* className Not a pure module */
