// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Strftime from "strftime";

var className = Curry._1(Css.style, /* :: */[
      Css.fontStyle(Css.italic),
      /* [] */0
    ]);

function Timestamp(Props) {
  var date = Props.date;
  var iso = date.toISOString();
  var formatted = Strftime("%d/%m/%Y %H:%M", date);
  return React.createElement("time", {
              className: className,
              dateTime: iso
            }, formatted);
}

var make = Timestamp;

export {
  className ,
  make ,
  
}
/* className Not a pure module */
