// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Style from "../Style.bs.js";
import * as React from "react";
import * as Strftime from "strftime";

var baseClassName = Curry._1(Css.style, {
      hd: Css.fontStyle(Css.italic),
      tl: /* [] */0
    });

function Timestamp(Props) {
  var className = Props.className;
  var date = Props.date;
  var iso = date.toISOString();
  var formatted = Strftime("%d/%m/%Y %H:%M", date);
  var className$1 = Style.combineClassNames({
        hd: baseClassName,
        tl: {
          hd: className,
          tl: /* [] */0
        }
      });
  return React.createElement("time", {
              className: className$1,
              dateTime: iso
            }, formatted);
}

var make = Timestamp;

export {
  baseClassName ,
  make ,
  
}
/* baseClassName Not a pure module */
